### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by ekremparlak** [UksusoFF/webtrees-reminder#12]
When try to send notification with url, email can't be send because module try to send email with admin's email address.
Webtrees logs:
````
MailService: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients "
````
Mail Server Logs:
 ````
NOQUEUE: reject: RCPT from hostname[ip]: 553 5.7.1 <myadminemail@domain.com>: Sender address rejected: not owned by user mail@domain.com; from=<myadminemail@domain.com> to=<myadminemail@domain.com> proto=ESMTP helo=<domain.com>
NOQUEUE: reject: RCPT from hostname[ip]: 553 5.7.1 <myadminemail@domain.com>: Sender address rejected: not owned by user mail@domain.com; from=<myadminemail@domain.com> to=<someuser@outlook.com> proto=ESMTP helo=<domain.com>
````
It works when i give permission to send email as myadminemail@domain.com to mail@domain.com

**Comment by UksusoFF** [comment]
Can you post screenshot of your /admin/email page?

**Comment by ekremparlak** [comment]
![Screenshot_2020-08-16 Sending email](https://user-images.githubusercontent.com/6561198/90329481-cadf3100-df94-11ea-946a-be0f5d067d70.png)

**Comment by ekremparlak** [comment]
I guess the problem is this module send email as contact user.
https://github.com/UksusoFF/webtrees-reminder/blob/3058d142b6ac77144d0113301360a03fb290466d/src/Http/Controllers/CronController.php#L125 should be change as `$author = $this->users->find((int)$tree->getPreference('SMTP_FROM_NAME')) ?: new SiteUser();`
There is a to do here;
https://github.com/UksusoFF/webtrees-reminder/blob/3058d142b6ac77144d0113301360a03fb290466d/src/Http/Controllers/CronController.php#L135

**Comment by UksusoFF** [comment]
Can you try latest master?

**Comment by ekremparlak** [comment]
Its now working with master

**Comment by UksusoFF** [comment]
Seems it's better way. In my instance CONTACT_USER_ID equals SMTP_FROM_NAME so it's worked.
