### ISSUE TITLE
User subscription

### ISSUE THREAD

**Issue by arbor95** [UksusoFF/webtrees-reminder#16]
Is it possible, that a user himself can subscribe for a reminder?
I only have seen a checkmark in the control page of the admin.

**Comment by UksusoFF** [comment]
In current realization - nope.

**Comment by UksusoFF** [comment]
@arbor95 please try latest master. Added this option on my-account page.

**Comment by arbor95** [comment]
I don't see a change on the my-account page.

**Comment by UksusoFF** [comment]
![image](https://user-images.githubusercontent.com/1931442/97779761-c4c31e80-1b99-11eb-93bc-a2334ed178c4.png)

Please check web page console. Any errors here? 

Also which theme you use?

**Comment by arbor95** [comment]
console:
DevTools failed to load SourceMap: Could not load content for http://web.bild-raum.de/public/css/webtrees.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://web.bild-raum.de/public/css/vendor.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://web.bild-raum.de/public/js/vendor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by UksusoFF** [comment]
Seems you not installed master version. Or reminder module disabled.
Because not found template on your site.

**Comment by arbor95** [comment]
I am sure I installed the master version: I disabled the old with reminder.disable and uploaded the unzipped master, but now I deleted both directories and uploaded again.
I was logged in as user and a refresh of the my-account user page gives the setting for the reminder. I disabled the reminder setting and logged out:
now the result for http://web.bild-raum.de/ is and access error:
Uncaught Fisharebest\Webtrees\Exceptions\HttpNotFoundException: Sie haben keine Berechtigung diese Seite anzusehen. in /mnt/web424/b0/69/5175769/htdocs/web/modules_v4/reminder/src/Modules/ReminderModule.php:171 Stack trace: #0 

is

        if ($user === null) {
            throw new HttpNotFoundException();
        }


/mnt/web424/b0/69/5175769/htdocs/web/modules_v4/reminder/src/Modules/ReminderModule.php(145): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->getSettingUserReminder() #1 /mnt/web424/b0/69/5175769/htdocs/web/resources/views/layouts/default.phtml(190): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->bodyContent() #2 [internal function]: Fisharebest\Webtrees\View::{closure}() #3 /mnt/web424/b0/69/5175769/htdocs/web/vendor/illuminate/support/Collection.php(1120): array_map() #4 /mnt/web424/b0/69/5175769/htdocs/web/resources/views/layouts/default.phtml(191): Illuminate\Support\Collection->map() #5 /mnt/web424/b0/69/5175769/htdocs/web/app/View.php(189): include('/mnt/web424/b0/...') #6 /mnt/web424/b0/69/5175769/htdocs/web/app/View.php(286): Fisharebest\Webtrees\View->rende

/mnt/web424/b0/69/5175769/htdocs/web/modules_v4/reminder/src/Modules/ReminderModule.php: 171

This error stays even I try to go back to the 2.0.4 version (by upload and .disable the master one)
On completely remove the master directory (not only doing .disable) makes the site work again.

**Comment by UksusoFF** [comment]
> I disabled the reminder setting and logged out:
now the result for http://web.bild-raum.de/ is and access error

It's bug, will fix it asap.

**Comment by UksusoFF** [comment]
> not only doing .disable

I'm not sure that webtrees realy disable it.

**Comment by UksusoFF** [comment]
@arbor95 please check update.

**Comment by arbor95** [comment]
setup works. where can i insert translation?

**Comment by UksusoFF** [comment]
No translation at now. Maybe will add it when release new version.

**Comment by UksusoFF** [comment]
@arbor95 Translations added. Welcome with German pull request.
