### ISSUE TITLE
PHP error on WT 2.0.10

### ISSUE THREAD

**Issue by Draky50110** [UksusoFF/webtrees-reminder#19]
Hello.

Tried to install in /modules_v4/ but got a full error page : 

`Error: Class 'UksusoFF\WebtreesModules\Reminder\Http\Controllers\AdminController' not found in /home/XXX/genealogie/modules_v4/reminder/src/Modules/ReminderModule.php:68 Stack trace: #0 /home/XXX/genealogie/app/Services/ModuleService.php(858): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->boot() #1 /home/XXX/genealogie/app/Http/Middleware/BootModules.php(60): Fisharebest\Webtrees\Services\ModuleService->bootModules(Object(Fisharebest\Webtrees\Module\WebtreesTheme)) #2 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #3 /home/XXX/genealogie/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #4 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #5 /home/XXX/genealogie/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #6 /home/XXX/genealogie/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #7 /home/XXX/genealogie/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3) #8 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 /home/XXX/genealogie/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 /home/XXX/genealogie/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 /home/XXX/genealogie/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 /home/XXX/genealogie/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /home/XXX/genealogie/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 /home/XXX/genealogie/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 /home/XXX/genealogie/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 /home/XXX/genealogie/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 /home/XXX/genealogie/app/Http/Middleware/BadBotBlocker.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 /home/XXX/genealogie/app/Http/Middleware/RegisterFactories.php(72): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 /home/XXX/genealogie/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /home/XXX/genealogie/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /home/XXX/genealogie/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 /home/XXX/genealogie/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 /home/XXX/genealogie/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 /home/XXX/genealogie/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 /home/XXX/genealogie/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 /home/XXX/genealogie/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 /home/XXX/genealogie/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /home/XXX/genealogie/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #46 {main}`

**Comment by UksusoFF** [comment]
Please show ```ls -la /home/XXX/genealogie/modules_v4/reminder/**``` from your server.

**Comment by Draky50110** [comment]
`-rw-rw-r-- 1 draky draky    170 Nov 26 13:29 modules_v4/reminder.disable/autoload.php
-rw-rw-r-- 1 draky draky    457 Nov 26 13:29 modules_v4/reminder.disable/composer.json
-rw-rw-r-- 1 draky draky  50305 Nov 26 13:29 modules_v4/reminder.disable/composer.lock
-rw-rw-r-- 1 draky draky    268 Nov 26 13:29 modules_v4/reminder.disable/module.php
-rw-rw-r-- 1 draky draky    895 Nov 26 13:29 modules_v4/reminder.disable/package.json
-rw-rw-r-- 1 draky draky 456338 Nov 26 13:29 modules_v4/reminder.disable/package-lock.json
-rw-rw-r-- 1 draky draky   1019 Nov 26 13:29 modules_v4/reminder.disable/README.md
-rw-rw-r-- 1 draky draky    498 Nov 26 13:29 modules_v4/reminder.disable/webpack.mix.js

modules_v4/reminder.disable/resources:
total 0
drwxrwxr-x 7 draky draky  74 Nov 26 13:29 .
drwxrwxr-x 4 draky draky 253 Nov 26 13:29 ..
drwxrwxr-x 2 draky draky  89 Nov 26 13:29 build
drwxrwxr-x 2 draky draky  48 Nov 26 13:29 langs
drwxrwxr-x 3 draky draky  36 Nov 26 13:29 scripts
drwxrwxr-x 3 draky draky  19 Nov 26 13:29 styles
drwxrwxr-x 4 draky draky  75 Nov 26 13:29 views

modules_v4/reminder.disable/src:
total 0
drwxrwxr-x 4 draky draky  36 Nov 26 13:29 .
drwxrwxr-x 4 draky draky 253 Nov 26 13:29 ..
drwxrwxr-x 2 draky draky  32 Nov 26 13:29 Helpers
drwxrwxr-x 2 draky draky  32 Nov 26 13:29 Modules
`

**Comment by UksusoFF** [comment]
Seems you missed files inside Helpers/Modules folders. Try unpack module and reupload again.

**Comment by Draky50110** [comment]
Thanks, I re-downloaded and now it works :)
