### ISSUE TITLE
where is the config page where the URL is located?

### ISSUE THREAD

**Issue by Joppla** [UksusoFF/webtrees-reminder#2]
Hello,

I like to use webtrees-reminder. In the instructions is written:

>  You can find this url on module config page.

But where can I find the config page? Probably I'm searching for the wrong item, but maybe you can give me a hint how to find.

Thanks for reaction.

**Comment by UksusoFF** [comment]
Hi @Joppla 

1. Login as admin
2. Go to My pages -> Control panel
3. Scroll to Modules
4. Click on Reminder title

**Comment by Joppla** [comment]
Thanks, I found it!

**Comment by Joppla** [comment]
Hm, I think I have made a correct cronjob, I don't get error messages any more, but also not an email. What can be the problem? I tested the email settings in webtrees and sent myself a test mail, that works.

**Comment by Joppla** [comment]
Or maybe it is only because there are no events today in my tree?

**Comment by UksusoFF** [comment]
> Or maybe it is only because there are no events today in my tree?

Yep. Reminder sends email only when today anniversaries exists.

**Comment by Joppla** [comment]
Thanks, tomorrow there is an event, than we know if it works. Have a nice evening. :-)

**Comment by UksusoFF** [comment]
@Joppla got it?

**Comment by Joppla** [comment]
@UksusoFF I didn't receive a mail. But I was thinking, how works the filtering of the events? Because this was a birthday of a living person. Can you inform me, that I can make a test for an event.

**Comment by UksusoFF** [comment]
Reminder should send birthday and marriage which displayed in "On this day" block.

**Comment by Joppla** [comment]
And has it to be on the "public" startpage block, or on my own startpage. Because a lot of events are hidden for public.

**Comment by UksusoFF** [comment]
It's doesn't matter. Reminder mimic user session for get events available for each user with enabled notify.

**Comment by Joppla** [comment]
Ok, in that case it didn't work. 

Have you any idea how can I test it to find out what is going wrong?

**Comment by UksusoFF** [comment]
You can manually go to url which triggered by cron. Do it and check email and page response.

**Comment by Joppla** [comment]
If I run the url I get an email, so something must be wrong in the cronjob. Thanks, now I can test the cronjob better

**Comment by Joppla** [comment]
The problem was that I was testing in my test environment and that is closed by .htaccess for all traffic except my own IP.  So also for traffic from the own server. ;)
