### ISSUE TITLE
not receiving e-mail

### ISSUE THREAD

**Issue by h4kk1** [UksusoFF/webtrees-reminder#30]
Hi, 
I have webtree installed on Synology NAS and is working very well. I wanted to have reminders from your module which I installed successfully (was able to see it in admin panel & cron task url etc.) When I execute the URL I dont receive e-mail - I have configured e-mail settings (SMTP server) which is working as well - just per your URL I dont get anything - I have it activated on my e-mail only. 
I didnt found any record in the log. 
Can you help me?

**Comment by UksusoFF** [comment]
Do you have any anniversaries for living peoples today?

**Comment by h4kk1** [comment]
Hi Kirill,
many thanks for the hint. I created test scenario and it is working very well! 
Just feeling ashamed :D. 

Sorry for disturbing ;) & wish all the best!
Daniel


⁣Získať BlueMail pre Android ​

19. máj 2021, 18:42, at 18:42, Kirill Uksusov ***@***.***> napísal:
