### ISSUE TITLE
Marriage/divorce

### ISSUE THREAD

**Issue by dax29** [UksusoFF/webtrees-reminder#36]
Hi
Is there a way to stop showing marriage anniversaries for couples that are now divorced.
Cheer
Dax

**Comment by slavkoja** [comment]
IMO, it is more webtrees issue than here, as they are shown in webtrees anniversaries too (at least for me).

**Comment by dax29** [comment]
Hi
Thanks for the quick response. Was asking as my previous marriage came up
even though I have it noted as being divorced
Cheers
___________________________________________________________
Frank & Sonia Kuilboer
68 Clark Lane
Broadwater  Queensland  4380 Australia

Mobile: 0439090856 (Frank), 0412214484 (Sonia)
Email: ***@***.*** or ***@***.***
Family History site: http://familytree.kuilboer.id.au/

**Comment by slavkoja** [comment]
Try to fill issue on webtrees project. You will get proper/better response with higher probability there, as i am user only too ;-)

**Comment by dax29** [comment]
Ok no worries Thanks for your help
___________________________________________________________
Frank & Sonia Kuilboer
68 Clark Lane
Broadwater  Queensland  4380 Australia

Mobile: 0439090856 (Frank), 0412214484 (Sonia)
Email: ***@***.*** or ***@***.***
Family History site: http://familytree.kuilboer.id.au/

**Comment by UksusoFF** [comment]
@dax29 
Please test latest master version
