### ISSUE TITLE
Email not containing complete data

### ISSUE THREAD

**Issue by MABeatty1978** [UksusoFF/webtrees-reminder#4]
I've got the module installed and running, but I'm getting an email that is incomplete.  I currently have 17 "On this day" events, but the email that I received only had 5.  All of them are Birth records.  None of the death or marriage records are sent.   I also noticed that some of them are living individuals which from my reading in another issue that was reported, these should not be displayed.

**Comment by UksusoFF** [comment]
> I currently have 17 "On this day" events, but the email that I received only had 5. All of them are Birth records. None of the death or marriage records are sent. 

This module send event if it's bithday (BITH) or marriage (MARR). Also event should be with living people. Death (DEAT) not should be sended.

> I also noticed that some of them are living individuals which from my reading in another issue that was reported, these should not be displayed.

Not sure that rigth understand. Please explain.

**Comment by MABeatty1978** [comment]
This is what I have for my current "On this day"

```
Record | Date | Anniversary | Event
-- | -- | -- | --
Kristine Bartlett | May 14, 1954 | 66 | Birth
Sylvester Harrison Beatty Wes | May 14, 1883 | 137 | Birth
George M Brennan | May 14, 1909 | 111 | Death
Robert Clemons | May 14, 1926 | 94 | Birth
Carleton Erdman | May 14, 1983 | 37 | Death
Francis J Hauser + Margaret May | May 14, 1902 | 118 | Marriage
Margaret Michelle Holzhauser Maggie | May 14, 2005 | 15 | Birth
John Kekelik Jack | May 14, 1932 | 88 | Birth
Edward Albert Maag | May 14, 1925 | 95 | Birth
William Battelle McEwen | May 14, 1864 | 156 | Death
Hartson McKillips | May 14, 1919 | 101 | Death
Elieen H Martin | May 14, 1913 | 107 | Birth
Joseph Mueller + Helena Rehberg | May 14, 1861 | 159 | Marriage
William H Overcasher | May 14, 1893 | 127 | Birth
William Ross | May 14, 1834 | 186 | Death
William Ross | May 14, 1739 | 281 | Birth
Maxim Tusin Rowe | May 14, 1880 | 140 | Birth
```
This is what I got in my email
```
14 May
Birth: Kristine Bartlett (1954 / 66)
Birth: Robert Clemons (1926 / 94)
Birth: Margaret Michelle Holzhauser Maggie (2005 / 15)
Birth: John Kekelik Jack (1932 / 88)
Birth: Edward Albert Maag (1925 / 95)
```

**Comment by UksusoFF** [comment]
Seems it's right.

It's not show because Death not included in module code:
```
George M Brennan | May 14, 1909 | 111 | Death
Carleton Erdman | May 14, 1983 | 37 | Death
William Battelle McEwen | May 14, 1864 | 156 | Death
Hartson McKillips | May 14, 1919 | 101 | Death
William Ross | May 14, 1834 | 186 | Death
```
It's not show because wife or husband is dead:
```
Francis J Hauser + Margaret May | May 14, 1902 | 118 | Marriage
Joseph Mueller + Helena Rehberg | May 14, 1861 | 159 | Marriage
```

It's not show because individual is dead:
```
Sylvester Harrison Beatty Wes | May 14, 1883 | 137 | Birth
Elieen H Martin | May 14, 1913 | 107 | Birth
William H Overcasher | May 14, 1893 | 127 | Birth
William Ross | May 14, 1739 | 281 | Birth
Maxim Tusin Rowe | May 14, 1880 | 140 | Birth
```

So we get 5 records which sended:
```
Kristine Bartlett | May 14, 1954 | 66 | Birth
Robert Clemons | May 14, 1926 | 94 | Birth
Margaret Michelle Holzhauser Maggie | May 14, 2005 | 15 | Birth
John Kekelik Jack | May 14, 1932 | 88 | Birth
Edward Albert Maag | May 14, 1925 | 95 | Birth
```

It's can be optional feature for sending all events. But it's really needed for dead people?

**Comment by MABeatty1978** [comment]
I understand now.  I misunderstood the purpose of this module.  It only
sends back reminders of living people.  I was intended on using it in a
different way.  I'm going to make some changes to the code to get the
results I'm looking for.  Thank you for your time.  You can resolve this
issue.
