### ISSUE TITLE
Incompatible with Webtrees 2.1.0

### ISSUE THREAD

**Issue by Vict0rC** [UksusoFF/webtrees-reminder#44]
Webtrees 2.1.0 has been released, and this module doesn't appear to be compatible.

**Comment by arbor95** [comment]
+1
first error: 'AbstractAdminController' not found

**Comment by UksusoFF** [comment]
Hi there! Try new version.

**Comment by dax29** [comment]
I installed the new version but am not getting any reminders, Speaking with Greg Roach my host he thinks the module might need some (small) updates for webtrees 2.1

**Comment by arbor95** [comment]
For me, the updated version works. You can have a look to the output of the cron job, to see details of your error!

**Comment by dax29** [comment]
> For me, the updated version works. You can have a look to the output of the cron job, to see details of your error!

Reminder was working fine for me prior to webtrees 2.1. I've just deleted and reinstalled the module so will see if that works. Greg advise that the cron output is fine. Cheers
