### ISSUE TITLE
E-Mail not send in any case of an event

### ISSUE THREAD

**Issue by ThoMagnum** [UksusoFF/webtrees-reminder#47]
Hello,
I am running webtrees on a Synology within a Docker container. So far so good.
If I use the "reminder" addin, only a information for linving people will sen even if I used the display on "my page" to show up event from already died people too. I also selected some additional informations, but here I am not sure if everything should trigger an E-Mail.
How can I configure the remider modul to send E-Mail by all events which I used on the "Events" block on my page?

I appreciate your help.

Best regards, Thomas

**Comment by UksusoFF** [comment]
If you need dead people you can change this to false: https://github.com/UksusoFF/webtrees-reminder/blob/master/src/Http/Controllers/CronController.php#L105
