### ISSUE TITLE
Data for dead once

### ISSUE THREAD

**Issue by wp4711** [UksusoFF/webtrees-reminder#61]
Hi,
Is it possible to get the data of death people too? would like to have this.
greets

**Comment by UksusoFF** [comment]
Yes, try add `DEAT` to this array: https://github.com/UksusoFF/webtrees-reminder/blob/565fb46c0014749aa00932d862e56816d65308f4/src/Http/Controllers/CronController.php#L103

**Comment by wp4711** [comment]
> Yes, try add `DEAT` to this array:
> 
> https://github.com/UksusoFF/webtrees-reminder/blob/565fb46c0014749aa00932d862e56816d65308f4/src/Http/Controllers/CronController.php#L103

Thanks, I got it!
