### ISSUE TITLE
Not compatible to webtrees 2.2.1

### ISSUE THREAD

**Issue by HonkXL** [UksusoFF/webtrees-reminder#64]
In webtrees 2.2.1 I get this message:

Fatal error in module: reminder
Error: Call to undefined function UksusoFF\WebtreesModules\Reminder\Modules\app()

**Comment by phildtmm** [comment]
+1

**Comment by UksusoFF** [comment]
https://github.com/UksusoFF/webtrees-reminder/releases/tag/v2.1.2
