### ISSUE TITLE
Check key on run cron job

### ISSUE THREAD

**Issue by ddrury** [UksusoFF/webtrees-reminder#7]
Hi,

- Have just come across your module - congratulations - very nice. I've been looking to implement a CRON interface for some time and wonder if you'd mind me using your module as the basis for mine.
- However, you don't seem to be using the key parameter, shouldn't you be checking it in CronController::run?

**Comment by UksusoFF** [comment]
> Have just come across your module - congratulations - very nice. I've been looking to implement a CRON interface for some time and wonder if you'd mind me using your module as the basis for mine.

Sure :)

> However, you don't seem to be using the key parameter, shouldn't you be checking it in CronController::run?

Forgot it. Fixed.
